<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $storeManager  = $objectManager
                        ->get('Magento\Store\Model\StoreManagerInterface');
          $url = $storeManager->getStore()->getBaseUrl().'sitemap';
?><div class="copy-visa">
<div class="copyright">
    <span><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></span><a href="<?php echo $url;?>"> | Mapa del sitio</a>
</div>
<div class="icons-visa">
<img src="<?php echo $block->getViewFileUrl('images/estafeta.png'); ?>">
	
</div>
</div>