<?php
/**
 * Baz view template
 *
 * @var $block FooBarBlockBaz
 */

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $storeManager  = $objectManager
                        ->get('Magento\Store\Model\StoreManagerInterface');
          $url = $storeManager->getStore()->getBaseUrl().'contact';
?>
<div class="section">
<div class="title">
<h3><?php echo $block->getTitle(); 
 
?></h3>

</div>
<div class="box-content">

<ul>
                <li>  <a href="<?php echo $url;?>">contactanos</a>
                </li>
                <li>
                    <a href="<?php echo $url;?>">preguntas frecuentes</a>
                </li>
                <li>
                    <a href="<?php echo $url;?>"><i class="location"></i>localiza tu tienda</a>
                </li>
</ul>
</div>
</div>

