<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>

<div class="section secure">
    <div class="title">
        <h3>sellos de confianza</h3>
    </div>
    <div class="box-content">
        <img src="<?php echo $this->getViewFileUrl('images/logo-amipci.png'); ?>" />
        <img src="<?php echo $this->getViewFileUrl('images/logo-thawte.png'); ?>" />
    </div>
</div>
