<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<div class="mx-1">
    <div class="section">
        <div class="title">
            <h3>AYUDA</h3>
        </div>
        <div class="box-content">
            <ul>
                <li>
                    <a href="#">contactanos</a>
                </li>
                <li>
                    <a href="#">preguntas frecuentes</a>
                </li>
                <li>
                    <a href="#"><i class="location"></i>localiza tu tienda</a>
                </li>
            </ul>	
        </div>
    </div>

    <div class="section second">
        <div class="title">
            <h3>políticas</h3>
        </div>
        <div class="box-content">
            <ul>
                <li>
                    <a href="#">Políticas de devolución</a>
                </li>
                <li>
                    <a href="#">Políticas de venta</a>
                </li>
                <li>
                    <a href="#">gastos de envío</a>
                </li>
                <li>
                    <a href="#">aviso de privacidad</a>
                </li>
                <li>
                    <a href="#">términos y condiciones</a>
                </li>
            </ul>
        </div>
    </div>
</div>
